# Generated by Django 4.2.3 on 2023-08-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='student_name',
            new_name='department_name',
        ),
        migrations.AddField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_mail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
